name: CMake Win7App Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - run: |
        mkdir build
        cmake -B build -G "Visual Studio 17 2022" -A Win32 .
        cmake --build build --config Release
      working-directory: ${{ github.workspace }}
    - uses: actions/upload-artifact@v3
      with:
        name: WinApp
        path: build/Release/WinApp.exe
      if: success()
      
