name: CMake Win7App Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Configure CMake
      run: |
        mkdir build
        cd build
        cmake .. -G -A Win32
    - name: Build
      run: |
        cmake --build . --config Release
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: WinApp
        path: build/Release/WinApp.exe
